## <b>SEMANA 5-6: NumPy - Computación Numérica Eficiente</B>

Temas:

- Introducción a NumPy y los arrays NumPy (ndarrays).
- Diferencias entre listas de Python y arrays NumPy - Ventajas de NumPy en rendimiento y funcionalidad para operaciones numéricas.
- Creación de arrays NumPy (a partir de listas, con funciones como arange, linspace, zeros, ones, random.rand, etc.).
- Tipos de datos en NumPy arrays (dtype).
- Indexación y slicing de arrays NumPy (similar a listas, pero con capacidades avanzadas).
- Operaciones aritméticas con arrays NumPy (elemento a elemento, operaciones con escalares).
- Funciones universales (ufuncs) de NumPy (funciones matemáticas, trigonométricas, lógicas, etc. aplicadas a arrays completos).
- Álgebra lineal básica con NumPy (dot product, transpose, etc.).
- Broadcasting en NumPy - Concepto importante para operaciones entre arrays de diferentes formas.

### Introducción a NumPy y los Arrays NumPy (ndarrays)

#### ¿Qué es NumPy?

NumPy (Numerical Python) es una librería de Python de código abierto que se utiliza para realizar computación numérica de manera eficiente.  Es especialmente poderosa para trabajar con arrays multidimensionales (vectores, matrices y arrays de dimensiones superiores) y realizar operaciones matemáticas en estos arrays de forma rápida y optimizada.

NumPy es una de las librerías más importantes en el ecosistema científico de Python.  Muchas otras librerías populares, como Pandas (para análisis de datos tabulares), SciPy (para computación científica y técnica), Matplotlib (para visualización de datos) y scikit-learn (para aprendizaje automático), se construyen sobre NumPy y utilizan sus arrays como estructura de datos fundamental.

#### Arrays NumPy (ndarrays): la estructura de datos clave

El núcleo de NumPy es el array NumPy, también conocido como ndarray (N-dimensional array). Un array NumPy es una estructura de datos similar a una lista o una matriz, pero con características especiales que lo hacen mucho más eficiente para operaciones numéricas:

- Homogeneidad de tipo de datos: Todos los elementos de un array NumPy deben ser del mismo tipo de dato (ej. todos enteros, todos flotantes, todos booleanos, etc.). Esta homogeneidad permite a NumPy almacenar los datos de manera más compacta en la memoria y realizar operaciones de forma optimizada.
- Tamaño fijo: Los arrays NumPy generalmente tienen un tamaño fijo al ser creados. Aunque existen formas de redimensionar arrays, las operaciones son más eficientes cuando el tamaño no cambia constantemente.
- Multidimensionalidad: Los arrays NumPy pueden tener múltiples dimensiones. Los más comunes son:
    - Arrays 1D (Vectores): Similares a listas, pero con las ventajas de NumPy.
    - Arrays 2D (Matrices): Filas y columnas, ideales para representar datos tabulares o matrices matemáticas.
    - Arrays 3D, 4D, ... ND: Arrays de dimensiones superiores, útiles para representar datos más complejos como imágenes (3D: alto, ancho, canales de color), videos (4D: tiempo, alto, ancho, canales de color), datos volumétricos, etc.

#### Ventajas de los Arrays NumPy:

Los arrays NumPy ofrecen varias ventajas importantes en comparación con las listas de Python para tareas numéricas:

- Rendimiento (Velocidad): Las operaciones numéricas en arrays NumPy son mucho más rápidas que las operaciones equivalentes en listas de Python, especialmente para grandes conjuntos de datos.  Esto se debe a que:

    - Implementación en C: NumPy está implementado en gran parte en C, un lenguaje de bajo nivel que es muy rápido en ejecución. Las operaciones de NumPy están altamente optimizadas y compiladas, lo que las hace más veloces que el código Python interpretado.
    - Almacenamiento Contiguo en Memoria: Los arrays NumPy almacenan los datos de manera contigua en la memoria (bloques de memoria adyacentes). Esto permite un acceso más rápido a los datos y operaciones más eficientes.
    - Operaciones Vectorizadas: NumPy permite realizar operaciones vectorizadas, es decir, aplicar operaciones a arrays completos (o "vectores") en una sola instrucción, en lugar de tener que iterar elemento por elemento con bucles for en Python. La vectorización es una de las claves del rendimiento de NumPy.
- Funcionalidad Extensa para Computación Numérica: NumPy proporciona una gran cantidad de funciones y herramientas para realizar operaciones numéricas comunes:

    - Operaciones aritméticas básicas (+, -, *, /, **, etc.) elemento a elemento.
    - Funciones matemáticas (trigonométricas, exponenciales, logarítmicas, etc.).
    - Álgebra lineal (multiplicación de matrices, determinantes, inversas, etc.).
    - Estadística (media, mediana, desviación estándar, etc.).
    - Generación de números aleatorios.
    - Transformaciones de arrays (reshape, transpose, etc.).
    - Operaciones de ordenamiento, búsqueda, etc.
    - Y mucho más...
- Menor Uso de Memoria: Debido a la homogeneidad de tipo de datos y al almacenamiento compacto, los arrays NumPy suelen ocupar menos memoria que las listas de Python para almacenar la misma cantidad de datos numéricos, especialmente para arrays grandes

### Diferencias entre Listas de Python y Arrays NumPy: Ventajas de NumPy en Rendimiento y Funcionalidad

Para entender mejor las ventajas de NumPy, veamos algunas diferencias clave entre las listas de Python y los arrays NumPy:


| Característica | Listas de Python	| Arrays NumPy (ndarrays) |
| --- | --- | --- |
| Tipo de datos	| Heterogéneo (elementos de diferentes tipos) | Homogéneo (todos los elementos del mismo tipo) | 
| Almacenamiento | No contiguo en memoria | Contiguo en memoria | 
| Tamaño | Dinámico (puede cambiar)	| Generalmente fijo (más eficiente) | 
| Rendimiento (Velocidad) | Más lento para operaciones numéricas | Mucho más rápido para operaciones numéricas | 
| Funcionalidad numérica | Limitada	| Extensa (funciones matemáticas, álgebra lineal, etc.) | 
| Uso de memoria | Mayor | Menor (generalmente) | 
| Vectorización	| No directamente soportada	| Totalmente soportada | 



    Ejemplo Comparativo de Rendimiento:

Vamos a comparar el tiempo que tarda en realizar una operación simple (sumar elementos) con una lista de Python y con un array NumPy:



In [1]:
import numpy as np
import time

# Crear una lista de Python grande
lista_python = list(range(1_000_000)) # Un millón de números

# Crear un array NumPy equivalente
array_numpy = np.array(lista_python)

# Sumar los elementos de la lista de Python (con bucle)
inicio_tiempo_lista = time.time()
suma_lista = 0
for numero in lista_python:
    suma_lista += numero
tiempo_lista = time.time() - inicio_tiempo_lista

# Sumar los elementos del array NumPy (operación vectorizada)
inicio_tiempo_array = time.time()
suma_array = np.sum(array_numpy) # Suma vectorizada con np.sum()
tiempo_array = time.time() - inicio_tiempo_array

print(f"Suma con lista de Python: {suma_lista}, tiempo: {tiempo_lista:.6f} segundos")
print(f"Suma con array NumPy: {suma_array}, tiempo: {tiempo_array:.6f} segundos")

# Deberías ver que la suma con NumPy es significativamente más rápida.

Suma con lista de Python: 499999500000, tiempo: 0.296754 segundos
Suma con array NumPy: 499999500000, tiempo: 0.000000 segundos




En este ejemplo, verás que la suma de un millón de números usando un array NumPy (con np.sum(), que está vectorizada) es mucho más rápida (a menudo, órdenes de magnitud más rápida) que la suma equivalente realizada con un bucle for en una lista de Python.  Esta diferencia de rendimiento se hace aún más notable a medida que aumenta el tamaño de los datos y la complejidad de las operaciones numéricas.

### Creación de Arrays NumPy

Hay varias formas de crear arrays NumPy:

#### A partir de listas de Python:

Puedes convertir una lista de Python (o una lista de listas, para arrays 2D, etc.) a un array NumPy usando la función `np.array()`:

In [ ]:
import numpy as np

lista1d = [1, 2, 3, 4, 5]
array1d = np.array(lista1d)
print(array1d) # Output: [1 2 3 4 5]
print(type(array1d)) # Output: <class 'numpy.ndarray'>
print(array1d.ndim) # Output: 1 (dimensión)
print(array1d.shape) # Output: (5,) (forma: 5 elementos en 1 dimensión)
print(array1d.dtype) # Output: int64 (tipo de datos: enteros de 64 bits)

lista2d = [[1, 2, 3], [4, 5, 6]]
array2d = np.array(lista2d)
print(array2d)
# Output:
# [[1 2 3]
#  [4 5 6]]
print(array2d.ndim) # Output: 2 (dimensiones)
print(array2d.shape) # Output: (2, 3) (forma: 2 filas, 3 columnas)
print(array2d.dtype) # Output: int64 (tipo de datos: enteros de 64 bits)

#### Funciones de creación de arrays con valores iniciales:

NumPy proporciona funciones convenientes para crear arrays con valores iniciales específicos:

- `np.zeros(forma)`: Crea un array con la forma especificada, lleno de ceros.
- `np.ones(forma)`: Crea un array con la forma especificada, lleno de unos.
- `np.full(forma, valor)`: Crea un array con la forma especificada, lleno con el valor dado.
- `np.empty(forma)`: Crea un array con la forma especificada, sin inicializar los valores (los valores iniciales serán lo que haya en la memoria en ese momento, generalmente "basura").  `np.empty()` es más rápido que `np.zeros()` o `np.ones()` porque no inicializa los valores, pero debes tener cuidado al usarlo si necesitas valores iniciales definidos


In [ ]:
# np.zeros(forma)
ceros_1d = np.zeros(5) # Array 1D de 5 ceros (por defecto, tipo flotante)
print(ceros_1d) # Output: [0. 0. 0. 0. 0.]
ceros_2d = np.zeros((2, 3)) # Array 2D de 2x3 ceros
print(ceros_2d)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]
ceros_int = np.zeros((2, 2), dtype=int) # Array 2D de 2x2 ceros, tipo entero
print(ceros_int)
# Output:
# [[0 0]
#  [0 0]]

# np.ones(forma)
unos_2d = np.ones((3, 2)) # Array 2D de 3x2 unos (por defecto, tipo flotante)
print(unos_2d)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

# np.full(forma, valor)
relleno_5 = np.full((2, 4), 5) # Array 2D de 2x4 lleno de 5
print(relleno_5)
# Output:
# [[5 5 5 5]
#  [5 5 5 5]]

# np.empty(forma)
vacio_3d = np.empty((2, 2, 2)) # Array 3D de 2x2x2 sin inicializar (valores aleatorios)
print(vacio_3d)
# Output: (valores aleatorios, pueden variar)


#### Funciones para crear secuencias numéricas:

- `np.arange(inicio, fin, paso)`: Similar a `range()` de Python, pero crea un array NumPy con valores en el rango `[inicio, fin]` (sin incluir `fin`), con un `paso` entre cada valor.
- `np.linspace(inicio, fin, num_puntos)`: Crea un array con `num_puntos` valores igualmente espaciados en el intervalo `[inicio, fin]` (incluyendo `fin` por defecto).  Muy útil para generar ejes para gráficos, por ejemplo.

In [ ]:
# np.arange(inicio, fin, paso)
rango_array = np.arange(0, 10, 2) # Array con valores de 0 a 8, de 2 en 2
print(rango_array) # Output: [0 2 4 6 8]

# np.linspace(inicio, fin, num_puntos)
lineal_array = np.linspace(0, 1, 5) # Array con 5 valores linealmente espaciados entre 0 y 1 (inclusive)
print(lineal_array) # Output: [0.   0.25 0.5  0.75 1.  ]


[0 3 6 9]
[0.   0.25 0.5  0.75 1.  ]


#### Funciones para crear arrays aleatorios:

El submódulo `random dentro` de NumPy `(np.random)` proporciona funciones para generar arrays con números aleatorios de diferentes distribuciones:

- `np.random.rand(forma)`: Crea un array con la `forma` especificada, lleno de números aleatorios con distribución uniforme en el intervalo `[0, 1]`.
- `np.random.randn(forma)`: Crea un array con la `forma` especificada, lleno de números aleatorios con distribución normal estándar (media 0, desviación estándar 1).
- `np.random.randint(inicio, fin, forma)`: Crea un array con la `forma` especificada, lleno de enteros aleatorios en el rango `[inicio, fin)` (sin incluir `fin`).


In [ ]:
# np.random.rand(forma)
aleatorio_uniforme = np.random.rand(3, 3) # Array 2D de 3x3 con números aleatorios uniformes [0, 1)
print(aleatorio_uniforme)
# Output: (valores aleatorios, varían cada vez)

# np.random.randn(forma)
aleatorio_normal = np.random.randn(2, 4) # Array 2D de 2x4 con números aleatorios normales estándar
print(aleatorio_normal)
# Output: (valores aleatorios, varían cada vez)

# np.random.randint(inicio, fin, forma)
enteros_aleatorios = np.random.randint(1, 10, (4, 4)) # Array 2D de 4x4 con enteros aleatorios entre 1 y 9 (inclusive)
print(enteros_aleatorios) # Output: (valores aleatorios, varían cada vez)


### Tipos de Datos en Arrays NumPy (`dtype`):

Como mencionamos, los arrays NumPy son homogéneos, lo que significa que todos los elementos de un array deben ser del mismo tipo de dato.  El tipo de dato de un array NumPy se especifica con el atributo `dtype` (data type).

#### Tipos de datos comunes en NumPy:

Algunos tipos de datos comunes en NumPy son:

- Enteros:
    - `np.int8`, `np.int16`, `np.int32`, `np.int64` (enteros con diferente número de bits, 8, 16, 32, 64)
    - `np.uint8`, `np.uint16`, `np.uint32`, `np.uint64` (enteros sin signo)
- Flotantes (punto flotante):
    - `np.float16`, `np.float32`, `np.float64` (flotantes de precisión simple, doble, extendida)
- Booleanos:
    - `np.bool_` (valores `True` o `False`)
- Cadenas (strings):
    - `np.str_` o `np.unicode_` (cadenas de longitud fija)
- Complejos:
    - `np.complex64`, `np.complex128` (números complejos)
- Objetos Python:
    - `np.object_` (para almacenar objetos Python arbitrarios, menos eficiente numéricamente)

#### Especificar dtype al crear arrays:

Puedes especificar el tipo de dato (`dtype`) al crear un array NumPy usando el argumento `dtype` en las funciones de creación:

In [11]:
enteros_int32 = np.array([1, 2, 3], dtype=np.int32)
print(enteros_int32.dtype) # Output: int32

flotantes_float64 = np.array([1.0, 2.5, 3.7], dtype=np.float64)
print(flotantes_float64.dtype) # Output: float64

booleanos = np.array([True, False, True], dtype=np.bool_)
print(booleanos.dtype) # Output: bool

int32
float64
bool


#### Conversión de tipo de datos (`astype`)

Puedes cambiar el tipo de dato de un array NumPy existente usando el método `.astype(nuevo_dtype)`:


In [ ]:
array_original = np.array([1, 2, 3]) # Tipo de dato por defecto: int64
array_flotante = array_original.astype(np.float64) # Convertir a flotante
print(array_flotante.dtype) # Output: float64
print(array_flotante) # Output: [1. 2. 3.]

array_booleano = array_original.astype(np.bool_) # Convertir a booleano
print(array_booleano.dtype) # Output: bool
print(array_booleano) # Output: [ True  True  True] (cualquier número diferente de 0 se convierte a True)

array_entero_a_string = array_original.astype(np.str_) # Convertir a cadena
print(array_entero_a_string.dtype) # Output: <U216 (cadena unicode, longitud máxima 216 caracteres)
print(array_entero_a_string) # Output: ['1' '2' '3']


### Indexación y Slicing de Arrays NumPy

La indexación y el slicing en arrays NumPy son muy similares a las listas de Python, pero con algunas capacidades avanzadas adicionales, especialmente para arrays multidimensionales.

#### Indexación Básica (similar a listas):

Indexación con un solo índice para acceder a elementos individuales:

In [14]:
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d[0]) # Output: 10 (primer elemento)
print(array_1d[2]) # Output: 30 (tercer elemento)
print(array_1d[-1]) # Output: 50 (último elemento, indexación negativa)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d[0, 0]) # Output: 1 (elemento en la fila 0, columna 0)
print(array_2d[1, 2]) # Output: 6 (elemento en la fila 1, columna 2)



10
30
50
1
6


#### Slicing (similar a listas, pero multidimensional):

##### Slicing 1D (similar a listas):


In [15]:
array_1d = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
print(array_1d[1:5]) # Output: [1 2 3 4] (elementos desde el índice 1 hasta 4, sin incluir el 5)
print(array_1d[:3]) # Output: [0 1 2] (elementos desde el inicio hasta el índice 2, sin incluir el 3)
print(array_1d[5:]) # Output: [5 6 7 8 9] (elementos desde el índice 5 hasta el final)
print(array_1d[::2]) # Output: [0 2 4 6 8] (elementos desde el inicio hasta el final, con paso 2)


[1 2 3 4]
[0 1 2]
[5 6 7 8 9]
[0 2 4 6 8]


##### Slicing 2D (y multidimensional):

Para arrays 2D (matrices), puedes usar slicing para seleccionar submatrices completas o partes de filas y columnas:



In [ ]:
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
# Output array_2d:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

print(array_2d[:2, :]) # Output: Las primeras 2 filas, todas las columnas
# [[1 2 3 4]
#  [5 6 7 8]]

print(array_2d[:, 1:3]) # Output: Todas las filas, columnas desde el índice 1 hasta 2 (sin incluir el 3)
# [[ 2  3]
#  [ 6  7]
#  [10 11]]

print(array_2d[1:, 2:]) # Output: Filas desde el índice 1 hasta el final, columnas desde el índice 2 hasta el final
# [[ 7  8]
#  [11 12]]

print(array_2d[::2, ::2]) # Output: Filas y columnas con paso 2
# [[ 1  3]
#  [ 9 11]]

print(array_2d[:2, 1:])


#### Indexación con arrays de índices (Indexación Avanzada):

NumPy permite la indexación avanzada usando arrays de índices enteros o booleanos, lo que proporciona una gran flexibilidad para seleccionar elementos de arrays basados en condiciones o índices específicos.

##### Indexación con arrays de índices enteros:


In [21]:
array_1d = np.arange(10, 60, 10) # [10 20 30 40 50]
indices = np.array([1, 3, 2]) # Índices que queremos seleccionar
elementos_seleccionados = array_1d[indices]
print(elementos_seleccionados) # Output: [20 40 30] (elementos en los índices 1, 3, 2)

array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])
# Output array_2d:
# [[10 20 30]
#  [40 50 60]
#  [70 80 90]]

indices_filas = np.array([0, 2]) # Filas que queremos seleccionar
indices_columnas = np.array([1, 2]) # Columnas que queremos seleccionar
submatriz_seleccionada = array_2d[indices_filas, indices_columnas]
print(submatriz_seleccionada) # Output: [20 90] (elementos en (fila 0, columna 1) y (fila 2, columna 2))

[20 40 30]
[20 90]


##### Indexación booleana (con arrays booleanos):

Puedes usar un array booleano (de la misma forma que el array original) para seleccionar elementos donde el array booleano es True.  Esto es muy útil para filtrar arrays basados en condiciones:


In [ ]:
array_1d = np.arange(10, 60, 10) # [10 20 30 40 50]
mascara_booleana = np.array([True, False, True, False, True]) # Máscara booleana
elementos_filtrados = array_1d[mascara_booleana] # Selecciona elementos donde la máscara es True
print(elementos_filtrados) # Output: [10 30 50] (elementos en índices 0, 2, 4)

array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
# Output array_2d:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

mascara_condicion = array_2d > 5 # Crea una máscara booleana donde los elementos > 5 son True
print(mascara_condicion)
# Output:
# [[False False False False]
#  [False  True  True  True]
#  [ True  True  True  True]]

elementos_filtrados_condicion = array_2d[mascara_condicion] # Selecciona los elementos donde la máscara es True
print(elementos_filtrados_condicion) # Output: [ 6  7  8  9 10 11 12] (elementos mayores que 5)

array_2d[mascara_condicion] = 0 # Asigna 0 a los elementos donde la máscara es True
print(array_2d)
# Output:
# [[1 2 3 4]
#  [5 0 0 0]
#  [0 0 0 0]] (elementos mayores que 5 ahora son 0)





### Operaciones Aritméticas con Arrays NumPy

Una de las grandes ventajas de NumPy es la facilidad para realizar operaciones aritméticas elemento a elemento en arrays y operaciones con escalares (números individuales).  Estas operaciones están vectorizadas, lo que las hace muy rápidas.

#### Operaciones Elemento a Elemento (con arrays de la misma forma):

Las operaciones aritméticas binarias (+, -, *, /, **, %) cuando se aplican a arrays NumPy de la misma forma, se realizan elemento a elemento.  El resultado es un nuevo array con la misma forma, donde cada elemento es el resultado de la operación correspondiente entre los elementos de los arrays de entrada.


In [28]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

suma_arrays = array_a + array_b # Suma elemento a elemento
print(suma_arrays) # Output: [5 7 9]

resta_arrays = array_b - array_a # Resta elemento a elemento
print(resta_arrays) # Output: [3 3 3]

producto_arrays = array_a * array_b # Producto elemento a elemento
print(producto_arrays) # Output: [ 4 10 18]

division_arrays = array_b / array_a # División elemento a elemento (¡cuidado con división por cero!)
print(division_arrays) # Output: [4.  2.5 2. ]

potencia_arrays = array_a ** 2 # Potencia elemento a elemento (array_a al cuadrado)
print(potencia_arrays) # Output: [1 4 9]


[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]


#### Operaciones con Escalares (Broadcasting Implícito):

También puedes realizar operaciones aritméticas entre un array NumPy y un escalar (un número individual).  En este caso, la operación se realiza entre el escalar y cada elemento del array (esto es un ejemplo simple de broadcasting, que veremos en detalle más adelante).

In [29]:
array_1d = np.array([1, 2, 3, 4, 5])
escalar = 2

suma_escalar = array_1d + escalar # Suma escalar a cada elemento del array
print(suma_escalar) # Output: [3 4 5 6 7]

multiplicacion_escalar = array_1d * escalar # Multiplica cada elemento del array por el escalar
print(multiplicacion_escalar) # Output: [ 2  4  6  8 10]

division_escalar = array_1d / escalar # Divide cada elemento del array por el escalar
print(division_escalar) # Output: [0.5 1.  1.5 2.  2.5]


[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


### Funciones Universales (`ufuncs`) de NumPy

NumPy proporciona una gran colección de funciones universales, abreviadas como `ufuncs`.  Las `ufuncs` son funciones que operan elemento a elemento sobre arrays NumPy, de manera muy eficiente y rápida (generalmente implementadas en `C`).

#### Tipos de `ufuncs`:

NumPy tiene `ufuncs` para diversas categorías:

- Funciones matemáticas: `np.sin()`, `np.cos()`, `np.exp()`, `np.log()`, `np.sqrt()`, `np.power()`, etc. (equivalentes vectorizadas de las funciones del módulo `math`).
- Funciones trigonométricas: `np.sin()`, `np.cos()`, `np.tan()`, `np.arcsin()`, `np.arccos()`, `np.arctan()`, `np.degrees()`, `np.radians()`, etc.
- Funciones de redondeo: `np.ceil()`, `np.floor()`, `np.round()`, `np.trunc()`, `np.fix()`.
- Funciones lógicas y de comparación: `np.logical_and()`, `np.logical_or()`, `np.logical_not()`, `np.equal()`, `np.not_equal()`, `np.greater()`, `np.less()`, etc.
- Funciones bit a bit: `np.bitwise_and()`, `np.bitwise_or()`, `np.bitwise_xor()`, `np.bitwise_not()`.
- Y muchas más...

#### Aplicación de `ufuncs` a arrays:

Cuando aplicas una `ufunc` a un `array` NumPy, la función se aplica a cada elemento del `array` de forma independiente, y retorna un nuevo `array` con los resultados.


In [31]:
array_1d = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
print(array_1d)

seno_array = np.sin(array_1d) # Calcula el seno de cada elemento del array
print(seno_array) # Output: [ 0.  1.  0. -1.  0.]

exponencial_array = np.exp(array_1d) # Calcula la exponencial de cada elemento
print(exponencial_array)
# Output: [1.         4.81047738 23.14069263 107.18866413 535.49165553]

raiz_cuadrada_array = np.sqrt(np.array([1, 4, 9, 16])) # Raíz cuadrada de cada elemento
print(raiz_cuadrada_array) # Output: [1. 2. 3. 4.]

array_a = np.array([True, False, True, False])
array_b = np.array([False, True, True, False])
and_logico_array = np.logical_and(array_a, array_b) # AND lógico elemento a elemento
print(and_logico_array) # Output: [False False  True False]


[0.         1.57079633 3.14159265 4.71238898 6.28318531]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
[  1.           4.81047738  23.14069263 111.31777849 535.49165552]
[1. 2. 3. 4.]
[False False  True False]


### Álgebra Lineal Básica con NumPy

NumPy proporciona funcionalidades básicas de álgebra lineal en su submódulo `numpy.linalg`. Algunas operaciones comunes son:

#### Multiplicación de matrices (`dot product`): 

 `np.dot(array_a, array_b)` calcula el producto punto (`dot product`) entre dos arrays.  Para matrices 2D, es la multiplicación matricial estándar. Para vectores 1D, es el producto escalar.



In [42]:
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6], [7, 8]])

producto_matrices = np.dot(matriz_a, matriz_b) # Multiplicación matricial
print(producto_matrices)
# Output:
# [[19 22]
#  [43 50]]

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
producto_escalar = np.dot(vector_a, vector_b) # Producto escalar (dot product de vectores 1D)
print(producto_escalar) # Output: 32 (1*4 + 2*5 + 3*6 = 32)


[[19 22]
 [43 50]]
32



#### Transpuesta de una matriz (transpose):
La transpuesta de una matriz es una matriz que se obtiene intercambiando las filas y columnas de la matriz original.

- `array.T` (o `np.transpose(array)`) retorna la transpuesta de un `array`.


In [ ]:
matriz_original = np.array([[1, 2, 3], [4, 5, 6]])
matriz_transpuesta = matriz_original.T # Transpuesta de la matriz
print(matriz_transpuesta)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

#### Determinante de una matriz (np.linalg.det):  

- `np.linalg.det(matriz)` calcula el determinante de una matriz cuadrada.


In [44]:
matriz_cuadrada = np.array([[1, 2], [3, 4]])
determinante = np.linalg.det(matriz_cuadrada)
print(determinante) # Output: -2.0 (1*4 - 2*3 = -2)


-2.0000000000000004


#### Inversa de una matriz (`np.linalg.inv`):  

`np.linalg.inv(matriz)` calcula la inversa de una matriz cuadrada invertible.


In [45]:
matriz_cuadrada = np.array([[1, 2], [3, 4]])
matriz_inversa = np.linalg.inv(matriz_cuadrada)
print(matriz_inversa)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]


[[-2.   1. ]
 [ 1.5 -0.5]]


#### Valores y vectores propios (`np.linalg.eig`):  

`np.linalg.eig(matriz)` calcula los valores propios y vectores propios de una matriz cuadrada.



In [46]:
matriz_cuadrada = np.array([[1, -2], [2, -3]])
valores_propios, vectores_propios = np.linalg.eig(matriz_cuadrada)
print("Valores propios:", valores_propios) # Output: Valores propios: [-1.+0.j -1.-0.j]
print("Vectores propios:\n", vectores_propios)
# Output Vectores propios:
# [[ 0.70710678+0.j -0.70710678-0.j]
#  [ 0.70710678+0.j  0.70710678-0.j]]



Valores propios: [-0.99999998 -1.00000002]
Vectores propios:
 [[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


### Broadcasting en NumPy: Operaciones con Arrays de Diferentes Formas

Broadcasting es una característica poderosa de NumPy que permite realizar operaciones aritméticas en arrays que tienen formas (shapes) diferentes, siempre y cuando sus formas sean "compatibles".  Broadcasting extiende la forma del array más pequeño para que coincida con la forma del array más grande durante la operación.

#### Reglas de Broadcasting:

##### NumPy aplica un conjunto de reglas para determinar si dos arrays tienen formas compatibles para broadcasting:

1. Dimensiones Compatibles: Dos dimensiones son compatibles si son iguales, o si una de ellas es 1.
2. Extensión de Dimensiones Unitarias: Si un array tiene menos dimensiones que el otro, NumPy "pre-pende" dimensiones unitarias (de tamaño 1) al principio de la forma del array más pequeño hasta que tenga el mismo número de dimensiones que el array más grande.
3. Compatibilidad de Todas las Dimensiones: Dos arrays son compatibles para broadcasting si, para cada par de dimensiones (comparando desde la última dimensión hacia la primera), las dimensiones son compatibles según la regla 1 (iguales o una es 1).

##### Ejemplos de Broadcasting:

- Escalar y Array:  Ya vimos el ejemplo de operar un escalar con un array. El escalar se "broadcast" para que coincida con la forma del array.


In [47]:
array_1d = np.array([1, 2, 3])
escalar = 2
suma = array_1d + escalar # Broadcasting del escalar
print(suma) # Output: [3 4 5]


[3 4 5]



- Array 1D y Array 2D:  Si tienes un array 1D y un array 2D, NumPy puede broadcast el array 1D a lo largo de las filas del array 2D si las dimensiones son compatibles.


In [48]:
array_1d_fila = np.array([1, 2, 3]) # Forma: (3,)
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]]) # Forma: (2, 3)

suma_broadcast = array_2d + array_1d_fila # Broadcasting de array_1d_fila a lo largo de las filas de array_2d
print(suma_broadcast)
# Output:
# [[11 22 33]
#  [41 52 63]]
# (array_1d_fila se "estiró" para convertirse en [[1, 2, 3], [1, 2, 3]] y luego se sumó elemento a elemento)

array_1d_columna = np.array([[1], [2], [3]]) # Forma: (3, 1) (array 2D con 1 columna)
array_2d_otro = np.array([[10, 20, 30],
                          [40, 50, 60]]) # Forma: (2, 3)

# ¡Broadcasting NO compatible en este caso! Formas (3, 1) y (2, 3) no son compatibles directamente.
# suma_broadcast_incompatible = array_2d_otro + array_1d_columna # Esto daría un error de broadcasting.
# Para hacer broadcasting "vertical" (a lo largo de columnas), podríamos necesitar transponer o resh

array_1d_columna_transpuesta = array_1d_columna.T # Transpuesta, forma: (1, 3)
suma_broadcast_compatible = array_2d_otro + array_1d_columna_transpuesta # Ahora formas (2, 3) y (1, 3) son compatibles
print(suma_broadcast_compatible)
# Output:
# [[11 21 31]
#  [42 52 62]]
# (array_1d_columna_transpuesta se "estiró" para [[1, 2, 3], [1, 2, 3]] y se sumó a array_2d_otro)



[[11 22 33]
 [41 52 63]]
[[11 22 33]
 [41 52 63]]


#### Ventajas del Broadcasting:

- Código Más Conciso: Permite realizar operaciones complejas en arrays de diferentes formas sin necesidad de bucles for explícitos para ajustar las formas manualmente.
- Mayor Eficiencia: Las operaciones con broadcasting están vectorizadas y optimizadas, lo que las hace más rápidas que las operaciones equivalentes con bucles.
- Flexibilidad: Aumenta la flexibilidad de NumPy para trabajar con arrays de diferentes dimensiones y formas.



### Ejemplos Prácticos

Vamos a consolidar lo que hemos aprendido con algunos ejemplos prácticos:

#### Crear arrays NumPy de diferentes formas y tipos:


In [49]:
import numpy as np

# Array 1D de enteros del 0 al 9
array_enteros_1d = np.arange(10, dtype=int)
print("Array 1D de enteros:\n", array_enteros_1d)

# Matriz 2D de flotantes de 3x4 llena de unos
matriz_unos_float = np.ones((3, 4), dtype=float)
print("\nMatriz 2D de unos (flotantes):\n", matriz_unos_float)

# Array 3D de enteros aleatorios entre 0 y 100, forma 2x3x2
array_aleatorio_3d = np.random.randint(0, 101, (2, 3, 2))
print("\nArray 3D de enteros aleatorios:\n", array_aleatorio_3d)


Array 1D de enteros:
 [0 1 2 3 4 5 6 7 8 9]

Matriz 2D de unos (flotantes):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array 3D de enteros aleatorios:
 [[[86 77]
  [50 62]
  [63 66]]

 [[61 34]
  [58  7]
  [71 42]]]



#### Realizar operaciones aritméticas entre arrays:


In [50]:
import numpy as np

array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])

suma_matrices = array_a + array_b
print("\nSuma de matrices:\n", suma_matrices)

producto_elemento_a_elemento = array_a * array_b
print("\nProducto elemento a elemento:\n", producto_elemento_a_elemento)

matriz_al_cuadrado = array_a ** 2
print("\nMatriz al cuadrado (elemento a elemento):\n", matriz_al_cuadrado)

matriz_transpuesta_a = array_a.T
print("\nTranspuesta de matriz_a:\n", matriz_transpuesta_a)



Suma de matrices:
 [[ 6  8]
 [10 12]]

Producto elemento a elemento:
 [[ 5 12]
 [21 32]]

Matriz al cuadrado (elemento a elemento):
 [[ 1  4]
 [ 9 16]]

Transpuesta de matriz_a:
 [[1 3]
 [2 4]]



#### Calcular la media, mediana, desviación estándar de un array NumPy:


In [51]:
import numpy as np

datos_array = np.array([12, 15, 20, 22, 25, 28, 30, 35, 40, 45])

media = np.mean(datos_array)
print("\nMedia:", media)

mediana = np.median(datos_array)
print("\nMediana:", mediana)

desviacion_estandar = np.std(datos_array)
print("\nDesviación estándar:", desviacion_estandar)



Media: 27.2

Mediana: 26.5

Desviación estándar: 10.067770358922576



#### Utilizar broadcasting para escalar una matriz por un vector:


In [52]:
import numpy as np

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector_escalar = np.array([0.5, 1, 1.5]) # Vector de escalado

matriz_escalada = matriz * vector_escalar # Broadcasting del vector para escalar columnas
print("\nMatriz escalada por vector (broadcasting):\n", matriz_escalada)


Matriz escalada por vector (broadcasting):
 [[ 0.5  2.   4.5]
 [ 2.   5.   9. ]
 [ 3.5  8.  13.5]]


## EJERCICIOS NumPy:

### Creación de Arrays:

- Crea un array NumPy 1D que contenga los números pares del 10 al 30 (inclusive).
- Crea una matriz 2D de 5x5 con todos los elementos iguales a 7.5.
- Crea un array 3D de forma (2, 3, 4) con números aleatorios enteros entre -10 y 10 (inclusive).

In [3]:
import numpy as np

array_1d = np.arange(10, 31, 2) # Array de 10 a 30, de 2 en 2
print(array_1d) # Output: [10 12 14 16 18 20 22 24 26 28 30]

array_2d = np.full((5, 5), 7.5) # Matriz 5x5 llena de 7.5
print(array_2d) 
# Output: [[7.5 7.5 7.5 7.5 7.5]
#          [7.5 7.5 7.5 7.5 7.5]
#          [7.5 7.5 7.5 7.5 7.5]
#          [7.5 7.5 7.5 7.5 7.5]
#          [7.5 7.5 7.5 7.5 7.5]]

array_3d = np.random.randint(-10, 10, (2, 3, 4)) # Array 3D de enteros aleatorios entre -10 y 10
print(array_3d) # Output: (valores aleatorios, varían cada vez)

[10 12 14 16 18 20 22 24 26 28 30]
[[7.5 7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5 7.5]]
[[[-2  3 -1  9]
  [-6 -5  8  9]
  [-2 -4  1  7]]

 [[-5  3 -7  6]
  [ 0  6 -9 -5]
  [-2  2 -5 -9]]]


### Indexación y Slicing:

Dado el siguiente array 2D:

```python
matriz_ejercicio = np.array([[11, 12, 13, 14, 15],
                             [21, 22, 23, 24, 25],
                             [31, 32, 33, 34, 35],
                             [41, 42, 43, 44, 45],
                             [51, 52, 53, 54, 55]])
```

- Extrae la segunda fila completa.
- Extrae la tercera columna completa.
- Extrae la submatriz de 3x3 que comienza en la esquina superior izquierda (filas 0-2, columnas 0-2).
- Extrae los elementos de la diagonal principal (11, 22, 33, 44, 55).
- Crea una máscara booleana para encontrar los elementos que son mayores que 30 y úsala para filtrar la matriz.

In [ ]:
import numpy as np

matriz_ejercicio = np.array([[11, 12, 13, 14, 15],
                             [21, 22, 23, 24, 25],
                             [31, 32, 33, 34, 35],
                             [41, 42, 43, 44, 45],
                             [51, 52, 53, 54, 55]])

print(matriz_ejercicio[1:2, :]) # Output: [[21 22 23 24 25]] (segunda fila)
print(matriz_ejercicio[:, 2:3]) # Output: [[13] [23] [33] [43] [53]] (tercera columna)
print(matriz_ejercicio[0:3, 0:3]) # Output: [[11 12 13] [21 22 23] [31 32 33]] (submatriz 3x3 en la esquina superior izquierda)
print(matriz_ejercicio.diagonal()) # Output: [11 22 33 44 55] (elementos de la diagonal principal)

mascara_booleana = matriz_ejercicio > 30 # Máscara booleana para elementos > 30
print(matriz_ejercicio[mascara_booleana]) # Output: [31 32 33 34 35 41 42 43 44 45 51 52 53 54 55] (elementos > 30)


### Operaciones Aritméticas y Ufuncs:

- Crea dos arrays NumPy 1D de la misma longitud (ej. 10 elementos cada uno) con números aleatorios enteros entre 1 y 20.
- Realiza las siguientes operaciones elemento a elemento entre los dos arrays: suma, resta, multiplicación, división, potencia.
- Calcula el seno, coseno y tangente de cada elemento del primer array usando ufuncs de NumPy.
- Calcula el logaritmo natural (base e) de cada elemento del segundo array (asegúrate de que no haya ceros o números negativos para evitar errores).

In [ ]:
import numpy as np

array_a = np.random.randint(1, 20, 10) # Array 1D de 10 enteros aleatorios entre 1 y 20
array_b = np.random.randint(0, 20, 10) # Array 1D de 10 enteros aleatorios entre 0 y 20 (¡posiblemente con ceros!)

suma = array_a + array_b # Suma de arrays
print(f'Suma:\n  {suma}')
resta = array_a - array_b # Resta de arrays
print(f'Resta:\n  {resta}')
producto = array_a * array_b # Producto de arrays
print(f'Producto:\n  {producto}')

# Consideración para división por cero:
array_b_sin_ceros = np.where(array_b == 0, 1e-9, array_b) # Reemplaza ceros en array_b por 1e-9
division = array_a / array_b_sin_ceros # División con array_b sin ceros (o con ceros reemplazados)
print(f'División (ceros reemplazados):\n  {division}')

potencia = array_a ** array_b # Potencia de arrays
print(f'Potencia:\n  {potencia}')

seno = np.sin(array_a) # Seno de array_a
print(f'Seno:\n  {seno}')
coseno = np.cos(array_a) # Coseno de array_a
print(f'Coseno:\n  {coseno}')
tangente = np.tan(array_a) # Tangente de array_a
print(f'Tangente:\n  {tangente}')

logaritmo = np.log(array_a) # Logaritmo natural de array_a
print(f'Logaritmo natural:\n  {logaritmo}')



### Álgebra Lineal Básica:

- Crea dos matrices cuadradas 2x2 (pueden ser aleatorias o definidas manualmente).
- Calcula la multiplicación matricial de las dos matrices.
- Calcula la transpuesta de la primera matriz.
- Calcula el determinante de la segunda matriz.
- Intenta calcular la inversa de la segunda matriz. ¿Qué pasa si la matriz no es invertible (determinante cercano a cero)? (No es necesario manejar la excepción, solo observa si obtienes un error o inf o nan en la matriz inversa).

In [35]:
import numpy as np

array2d_a = np.array([[1, 3], [4, 5]])
array2d_b = np.array([[ 8, 9], [10, 12]])

multiplicacion_matricial = np.dot(array2d_a, array2d_b) # Multiplicación matricial
print(f'Multiplicación matricial:\n  {multiplicacion_matricial}')

array2d_a_transpuesta = array2d_a.T # Transpuesta de array2d_a
print(f'Transpuesta de array2d_a:\n  {array2d_a_transpuesta}')

array2d_b_determinante = np.linalg.det(array2d_b) # Determinante de array2d_b
print(f'Determinante de array2d_b: {array2d_b_determinante}')

# Consideración para matrices no invertibles:
determinante_b = np.linalg.det(array2d_b)
tolerancia_determinante_cero = 1e-6  # Define una tolerancia (ej. 1e-6)

if abs(determinante_b) < tolerancia_determinante_cero: # Verifica si el determinante está cerca de cero
    print("\nError: La matriz array2d_b es singular (no invertible) porque su determinante está muy cerca de cero.")
    # En este caso, NO intentes calcular la inversa, o maneja el caso como consideres apropiado
    array2d_b_inversa = None # Podrías asignar None o un valor especial para indicar que no hay inversa
else:
    array2d_b_inversa = np.linalg.inv(array2d_b) # Inversa de array2d_b (solo si el determinante no es cercano a cero)
    print(f'Inversa de array2d_b:\n  {array2d_b_inversa}')

if array2d_b_inversa is not None: # Verifica si se calculó la inversa antes de intentar imprimirla (opcional)
    # ... (Aquí podrías realizar operaciones adicionales con la inversa si la calculaste)
    pass # Por ejemplo, podrías verificar si matriz_b * matriz_inversa es aproximadamente la matriz identidad

Multiplicación matricial:
  [[38 45]
 [82 96]]
Transpuesta de array2d_a:
  [[1 4]
 [3 5]]
Determinante de array2d_b: 6.000000000000016
Inversa de array2d_b:
  [[ 2.         -1.5       ]
 [-1.66666667  1.33333333]]


### Broadcasting:

- Crea una matriz 3x4 con números aleatorios entre 0 y 1.
- Crea un vector fila de 4 elementos con valores [10, 20, 30, 40].
- Utiliza broadcasting para sumar el vector fila a cada fila de la matriz.
- Crea un vector columna de 3 elementos con valores [[1], [2], [3]].
- Utiliza broadcasting para sumar el vector columna a cada columna de la matriz original (o de la matriz resultante del paso anterior, como prefieras)

In [ ]:
matriz = np.random.rand(3, 4) 
vector = np.arange(10, 50, 10)

suma_1 = matriz + vector
print(suma_1)

vector_columna = [[1], [2], [3]]
suma_2 = matriz + vector_columna
print(suma_2)

[[10.18033766 20.02436592 30.60924542 40.82943533]
 [10.2572353  20.08030361 30.27781937 40.36304273]
 [10.23994501 20.16628825 30.27499385 40.97330462]]
[[1.18033766 1.02436592 1.60924542 1.82943533]
 [2.2572353  2.08030361 2.27781937 2.36304273]
 [3.23994501 3.16628825 3.27499385 3.97330462]]
